=== learningtapestry/ssdn/packages/core/src/schemas/caliper-schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "type": "object",
  "title": "Caliper Envelope",
  "additionalProperties": false,
  "properties": {
    "sensor": {
      "id": "#sensor",
      "type": "string",
      "format": "iri"
    },
    "sendTime": {
      "id": "#sendTime",
      "type": "string",
      "format": "date-time"
    },
    "dataVersion": {
      "id": "#dataVersion",
      "type": "string",
      "format": "iri"
    },
    "data": {
      "id": "#activityid",
      "type": "array",
      "items": {
        "type": "object"
      }
    }
  },
  "required": ["sensor", "sendTime", "dataVersion", "data"]
}

=== learningtapestry/ssdn/packages/core/test-support/data-samples/caliper.json
{
  "sensor": "https://example.edu/sensors/1",
  "sendTime": "2018-11-15T11:05:01.000Z",
  "dataVersion": "http://purl.imsglobal.org/ctx/caliper/v1p1",
  "data": [
    {
      "@context": "http://purl.imsglobal.org/ctx/caliper/v1p1",
      "id": "urn:uuid:7e10e4f3-a0d8-4430-95bd-783ffae4d916",
      "type": "ToolUseEvent",
      "actor": {
        "id": "https://example.edu/users/554433",
        "type": "Person"
      },
      "action": "Used",
      "object": {
        "id": "https://example.edu",
        "type": "SoftwareApplication"
      },
      "eventTime": "2018-11-15T10:15:00.000Z",
      "edApp": "https://example.edu",
      "group": {
        "id": "https://example.edu/terms/201801/courses/7/sections/1",
        "type": "CourseSection",
        "courseNumber": "CPS 435-01",
        "academicSession": "Fall 2018"
      },
      "membership": {
        "id": "https://example.edu/terms/201801/courses/7/sections/1/rosters/1",
        "type": "Membership",
        "member": "https://example.edu/users/554433",
        "organization": "https://example.edu/terms/201801/courses/7/sections/1",
        "roles": ["Learner"],
        "status": "Active",
        "dateCreated": "2018-08-01T06:00:00.000Z"
      },
      "session": {
        "id": "https://example.edu/sessions/1f6442a482de72ea6ad134943812bff564a76259",
        "type": "Session",
        "startedAtTime": "2018-11-15T10:00:00.000Z"
      }
    }
  ]
}
